name: DuelsPE
author: corytortoise
main: corytortoise\DuelsPE\Main
version: "1.0"
api: [2.0.0]
description: 1vs1 plugin for PocketMine-MP based on Minifixio's 1vs1 plugin.

commands:
  duel:
    description: Main Duels command. Create, Join, or Delete an Arena.
    usage: "/duel <join | quit | 1 | 2 | create> [args]"